### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by natdon** [ffrige/RobControl#1]
Is there an example to use?
Thanks

**Comment by natdon** [comment]
There is a problem in the reverse solution. When the angle of the axis 5 is 90 degrees, the coordinate C is moved to 90 degrees. At this time, the machine does not move, and the sixth axis rotates.
The following are the parameters I use.

	Links[0].Offset.X = 0;
	Links[0].Offset.Y = 0;
	Links[0].Offset.Z = 0;
	Links[1].Offset.X = 4.8;
	Links[1].Offset.Y = 0;
	Links[1].Offset.Z = 7.3;
	Links[2].Offset.X = 0;
	Links[2].Offset.Y = 0;
	Links[2].Offset.Z = 13;
	Links[3].Offset.X = 1;
	Links[3].Offset.Y = 0;
	Links[3].Offset.Z = 2;
	Links[4].Offset.X = 13;
	Links[4].Offset.Y = 0;
	Links[4].Offset.Z = 0;
	Links[5].Offset.X = 3.6;
	Links[5].Offset.Y = 0;
	Links[5].Offset.Z = 0;

       JointAxes[0] = 0;
       JointAxes[1] = 0;
       JointAxes[2] = 0;
       JointAxes[3] = 0;
       JointAxes[4] = 90;
       JointAxes[5] = 0;

       PathAxes[0] = 18.8;
       PathAxes[1] = 0;
	PathAxes[2] = 18.7;
	PathAxes[3] = 0;
	PathAxes[4] = 90;
	PathAxes[5] = 50;
ArmInverse(Links, PathAxes, JointAxes, Axes);

The result is 0 0 0 0 90 -50

**Comment by ffrige** [comment]
The input to the ArmInverse function is the position of the path axes, in your case:
X=18.8; Y=0; Z=18.7; A=0; B=90; C=50.
The output is the Axes vector [0,0,0,0,90,-50], which is correct.
When facing down the joint Q6 rotates in the opposite direction of the C axis, following the right-hand rule. 
![image](https://user-images.githubusercontent.com/24692659/45612476-98b9b180-ba95-11e8-984a-4bf5672ed284.png)
