### ISSUE TITLE
A problem about calling function RobotControl

### ISSUE THREAD

**Issue by ZhaoYiChina** [ffrige/RobControl#3]
Hi, friend. How do you do these days?
There is a question about the monitor, which is that the program is running normally, but I can't see the monitor. 
![image](https://user-images.githubusercontent.com/25918987/89192616-5214c800-d5d7-11ea-9c3e-8b3967d9a3f2.png)

**Comment by ffrige** [comment]
The monitor is a component of the Robot_Type data structure.
For example, if you have two robots:
`Robot_Type Robot[2];`
Then the you can read the error on the second robot with:
`Robot[1].Monitor.ActiveError`

**Comment by ZhaoYiChina** [comment]
Thank you very much. I live in Shanghai, too. Do you have Wechat account? I want to make friends with you. Can I add your Wechat?
